# Generated by Django 2.2.19 on 2021-06-16 09:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='ip пользователя')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=tinymce.models.HTMLField(help_text='Напишите комменатрий', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(help_text='Что у вас нового?', verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='posts.Ip'),
        ),
    ]
