# Generated by Django 2.2.19 on 2021-06-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_pagehit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehit',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
