# Generated by Django 2.2.19 on 2021-06-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210617_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagehit',
            options={'ordering': ['client', '-count']},
        ),
    ]
